[[language]]
name = "just"
auto-format = true

[language.formatter]
command = "just"
args = ["--justfile", "/dev/stdin", "--dump"]

[[language]]
name = "markdown"
auto-format = true

[language.formatter]
command = "prettierd"
args = [".md"]

[[language]]
name = "nix"
auto-format = true

[language.formatter]
command = "alejandra"

[[language]]
name = "toml"
auto-format = true

[language.formatter]
command = "taplo"
args = ["format", "-"]

# just
[[language]]
name = "just"
auto-format = true
formatter = { command = "just", args = ["--justfile", "/dev/stdin", "--dump"] }

# markdown
[[language]]
name = "markdown"
auto-format = true
formatter = { command = "prettierd", args = [".md"] }

# nix
[[language]]
name = "nix"
auto-format = true
formatter = { command = "alejandra" }

# toml
[[language]]
name = "toml"
auto-format = true
formatter = { command = "taplo", args = ["format", "-"] }
