use-grammars = { only = ["lilypond"] }

[[language]]
name = "lilypond"
comment-token = "%"
file-types = ["ly", "ily"]
scope = "source.lilypond"

[[grammar]]
name = "lilypond"
source = { git = "https://github.com/nwhetsell/tree-sitter-lilypond", rev = "110f919a0fd7b4fca724baee67f0c5d1c07718d8" }
