#!/usr/bin/env zsh

files=($("${HELPERS}"/_get_files "ly" "$@"))
if [ -z "${files[*]}" ]; then
    exit
fi
for file in "${files[@]}"; do
    without_extension="${file:r}"
    pdf_files=("${PDFS_DIRECTORY}/${without_extension:t}"*.pdf)
    for file in "${pdf_files[@]}"; do
        checkexec "${file}" "${without_extension}"*.*ly(N) *.ily -- \
            echo "${file:r:t}"
    done
done
