#!/usr/bin/env zsh

join_with_separator() {
    local IFS="${1}"
    shift
    echo "$*"
}

IFS=" " read -r -A ARGS <<< "$@"
if ((${ARGS[(I)*--include-templates*]})); then
    include_templates="true"
    shift
fi

setopt extendedglob
extension="${1}"
shift
scores=("$@")
if [ -z "${scores[*]}" ]; then
    if [ "${extension}" = "pdf" ]; then
        files=($(join_with_separator \
                    ":" \
                    "${PDFS_DIRECTORY}"/*."${extension}"(N)))
    else
        if [ "${include_templates}" = "true" ]; then
            files=(**/**."${extension}"(N))
        else
            files=((^templates/)#*."${extension}"(N))
        fi
    fi
else
    files=()
    for file in "${scores[@]}"; do
        if [ "${extension}" = "pdf" ]; then
            files+=($(join_with_separator \
                        ":" \
                        "${PDFS_DIRECTORY}"/*"${file}"*."${extension}"(N)))
        else
            if [ "${include_templates}" = "true" ]; then
                files+=(**/**"${file}"*."${extension}"(N))
            else
                files+=((^templates/)#*"${file}"*."${extension}"(N))
            fi
        fi
    done
fi
printf "%s" "${files[*]}"
