#!/usr/bin/env zsh

IFS=" " read -r -A files <<<"$("${HELPERS}"/_get_files "ly" "$@")"
if [ -z "${files[*]}" ]; then
    exit
fi
for file in "${files[@]}"; do
    without_extension="${file:r}"
    pdf_file="${PDFS_DIRECTORY}/${without_extension:t}.pdf"
    checkexec "${pdf_file}" "${without_extension}"*.*ly(N) ./*.ily -- \
        echo "${pdf_file:t:r}"
done
