#!/usr/bin/env zsh

export COMMANDS="./scripts/commands"
export HELPERS="./scripts/helpers"
export PDFS_DIRECTORY="${PDFS_DIRECTORY:-./pdfs}"

command="${1}"
if [ -z "${command}" ]; then
    echo \
        "Available recipes:
    clean *scores    # Remove pdf(s).
    commit message   # Commit and push all files.
    compile *scores  # Create pdf(s).
    create type composer title *edit # Create new score template, and optionally edit ("--edit").
    edit score       # Open <score> in editor and pdf viewer, recompiling on file changes.
    install          # Install dependencies.
    list *scores     # List pdf(s).
    main *message    # Switch back to main branch, optionally committing the current branch.
    open *scores     # Open pdf(s).
    outdated *scores # List <scores> with outdated or non-existent pdfs.
    status *scores   # Show status of pdf(s) for <scores>.
    update *scores   # Update lilypond version in <scores>."
    exit
fi
shift
case "${command}" in
    "clean")
        "${COMMANDS}"/clean "$@"
        ;;
    "compile")
        "${COMMANDS}"/compile "$@"
        ;;
    "create")
        "${COMMANDS}"/create "$@"
        ;;
    "edit")
        "${COMMANDS}"/edit "$@"
        ;;
    "install")
        "${COMMANDS}"/install "$@"
        ;;
    "list")
        "${COMMANDS}"/list "$@"
        ;;
    "open")
        "${COMMANDS}"/open "$@"
        ;;
    "outdated")
        "${COMMANDS}"/outdated "$@"
        ;;
    "status")
        "${COMMANDS}"/status "$@"
        ;;
    "update")
        "${COMMANDS}"/update "$@"
        ;;
esac
