#!/usr/bin/env zsh

COMMANDS="./scripts/commands"
export HELPERS="./scripts/helpers"
export PDFS_DIRECTORY="${PDFS_DIRECTORY:-./pdfs}"

command="${1}"
if [ -z "${command}" ]; then
    echo "USAGE: './scripts/main <COMMAND> <ARGS>'\n"
    echo "Available commands:"
    available_commands=($(ls "${COMMANDS}"))
    for command in "${available_commands[@]}"; do
        echo "    ${command}"
    done
    exit
fi
shift
case "${command}" in
    "clean")
        "${COMMANDS}"/clean "$@"
        ;;
    "compile")
        "${COMMANDS}"/compile "$@"
        ;;
    "create")
        "${COMMANDS}"/create "$@"
        ;;
    "edit")
        "${COMMANDS}"/edit "$@"
        ;;
    "install")
        "${COMMANDS}"/install "$@"
        ;;
    "list")
        "${COMMANDS}"/list "$@"
        ;;
    "open")
        "${COMMANDS}"/open "$@"
        ;;
    "outdated")
        "${COMMANDS}"/outdated "$@"
        ;;
    "status")
        "${COMMANDS}"/status "$@"
        ;;
    "update")
        "${COMMANDS}"/update "$@"
        ;;
esac
