#!/usr/bin/env zsh

get_pdf_files() {
    score_title="${1:t:r}"
    pdf_files=("${PDFS_DIRECTORY}"/*"${score_title}"*(N))
    printf "%s" "${pdf_files[*]}"
}

lilypond -o "${PDFS_DIRECTORY}" "${1}"
if [ -n "${OUTPUT_DIRECTORY}" ]; then
    IFS=" " read -r -A pdf_files <<<"$(get_pdf_files "${1}")"
    for file in "${pdf_files[@]}"; do
        cp "${file}" "${OUTPUT_DIRECTORY}"
    done
fi
