#!/usr/bin/env zsh

files=($("${HELPERS}"/_get_files "ly" "$@"))
if [ -z "${files[*]}" ]; then
    exit
fi
for file in "${files[@]}"; do
    base_name="${PDFS_DIRECTORY}/${file:r:t}"
    score_files=("${base_name}"*.pdf(N))
    if [ -z "${score_files[*]}" ]; then
        lilypond -o "${PDFS_DIRECTORY}" "${file}"
    else
        for score_file in "${score_files[@]}"; do
            checkexec "${score_file}" "${without_extension}"*.*ly(N) *.ily -- \
                lilypond -o "${PDFS_DIRECTORY}" "${file}"
        done
    fi
done
