#!/usr/bin/env zsh

get_new_score_name () {
    if [ "${1}" = "piano" ]; then
        extension=".${2:e}"
    else
        extension="-${2:t}"
    fi
    file_name="${3}${extension}"
    printf "%s" "${4}/${file_name}"
}

prepend_titles() {
    filetypes=("changes" "lyrics" "melody" "structure")
    for filetype in "${filetypes[@]}"; do
        sed -i "" -e "s/${filetype}.ily/${1}-${filetype}.ily/g" "${2}"
    done
}

add_title_and_composer() {
    title="${(C)1}"
    composer="${(C)2}"
    sed -i "" -e "s/Title/${title}/g" "${3}"
    sed -i "" -e "s/Composer/${composer}/g" "${3}"
}

copy_template_files() {
    score_directory=./scores/"${2}"/"${3}"
    mkdir -p "${score_directory}"
    for template in ./templates/"${1}"*/*; do
        new_score="$(
            get_new_score_name \
                "${1}" "${template}" "${3}" "${score_directory}"
        )"
        if test -f "${new_score}"; then
            continue
        fi
        cp "${template}" "${score_directory}"
        mv "${score_directory}/${template:t}" "${new_score}"
        if [ "${new_score}" = "main.ly" ]; then
            prepend_titles "${3}" "${file}"
            add_title_and_composer "${3}" "${2}" "${file}"
            mv "${file}" "${file//-main/}"
        fi
    done
}

"${HELPERS}"/_checkout_branch "${3}"
copy_template_files "${1}" "${2}" "${3}"
if [ "${4}" = "--edit" ]; then
    just edit "${3}"
fi
