#!/usr/bin/env zsh

for file in **/**"${1}"*.ly(N); do
    without_extension="${file:r}"
    ly_file="${without_extension}.ly"
    IFS=" " read -r -A pdf_files <<<"$("${HELPERS}"/_get_pdf_files "${ly_file}")"
    for file in "${pdf_files[@]}"; do
        open "${file}"
    done
    open "${ly_file}"
done
watchexec -e ly,ily just compile "${1}"
