#!/usr/bin/env zsh

files=(**/**"${1}"*.ly(N))
if [ -z "${files[*]}" ]; then
    echo "No score matching \"${1}.\""
    exit
fi
for file in "${files[@]}"; do
    without_extension="${file:r}"
    ly_file="${without_extension}.ly"
    pdf_files=($("${HELPERS}"/_get_pdf_files "${ly_file}"))
    for file in "${pdf_files[@]}"; do
        open "${file}"
    done
    open "${ly_file}"
done
watchexec --exts ly,ily --clear "${COMMANDS}"/compile "${1}"
